# fly.toml app configuration file for qmaticshiftc
# See https://fly.io/docs/reference/configuration/ for information

app = 'qmaticshiftc'
primary_region = 'fra'

# Tell Fly how to run the app
[deploy]
  release_command = "npm start"

# This section configures the web service
[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

# This section creates the persistent volume for your SQLite database.
[mounts]
  source = "task_data"
  destination = "/data"

# This is the new, important section for Health Checks
[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.http_checks]]
    interval = "15s"
    timeout = "10s"
    method = "get"
    path = "/api/team" # We will check a real API endpoint
    grace_period = "30s" # Give the app 30 seconds to start up before checking

# This section defines the size of the virtual machine
[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1