# fly.toml app configuration file for qmaticshiftc
# This is the final and correct version.

app = 'qmaticshiftc'
primary_region = 'fra'

# This section defines how the app runs.
# This is the correct place for the start command.
[processes]
  app = "npm start"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source = "task_data"
  destination = "/data"

# This section defines how to check if the app is healthy.
[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.http_checks]]
    interval = "15s"
    timeout = "10s"
    method = "get"
    path = "/api/team"
    grace_period = "30s"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
